name: Collect Traffic Metrics

on:
  schedule:
    - cron: "0 2 * * *"   # Run daily at 2 AM UTC
  workflow_dispatch:       # Allow manual runs

jobs:
  fetch-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Fetch GitHub Traffic Metrics
        env:
          REPO: ${{ github.repository }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/fetch_traffic_metrics.py

      - name: Commit updated metrics
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add metrics/views.csv metrics/clones.csv
          git commit -m "Update traffic metrics for $(date +'%Y-%m-%d')" || echo "No changes"
          git push
